using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SekaiLink.Router.Generators;

[Generator]
public sealed class DeviceRouteRegistryGenerator : IIncrementalGenerator
{
    private const string AttributeName = "SekaiLink.Protocols.Routing.DeviceRouteProviderAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var providers = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (generatorContext, _) => (INamedTypeSymbol)generatorContext.TargetSymbol)
            .Where(static symbol => !symbol.IsAbstract)
            .Collect();

        context.RegisterSourceOutput(providers, static (sourceContext, symbols) =>
            EmitRegistry(sourceContext, symbols));
    }

    private static void EmitRegistry(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var names = new SortedSet<string>(symbols
            .Select(static symbol => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("namespace SekaiLink.Router");
        source.AppendLine("{");
        source.AppendLine("    internal static partial class DeviceRouteRegistry");
        source.AppendLine("    {");
        source.AppendLine(
            "        static partial void AddGenerated(global::System.Collections.Generic.ICollection<global::SekaiLink.Protocols.Routing.IDeviceRouteProvider> providers)");
        source.AppendLine("        {");
        foreach (var name in names)
            source.Append("            providers.Add(new ").Append(name).AppendLine("());");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        context.AddSource("DeviceRouteRegistry.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}